manager/urls.py
from django.urls import path

from . import views
from .views import add_volunteer, view_volunteer, events_list, view_event, add_event, delete_event, add_participation, \
    edit_volunteer, edit_event, generate_report, view_dashboard, volunteers_list, edit_participation

urlpatterns = [
    path("", view_dashboard, name="index"),
    path('dashboard', view_dashboard, name='view_dashboard'),
    path('volunteers', volunteers_list, name="volunteers_list"),
    path('add_volunteer', add_volunteer, name='add_volunteer'),
    path('view_volunteer/<int:user_id>/', view_volunteer, name='view_volunteer'),
    path('edit_volunteer/<int:user_id>/', edit_volunteer, name='edit_volunteer'),

    path('events/', events_list, name='events_list'),
    path('events/add/', add_event, name='add_event'),
    path('events/<int:event_id>/', view_event, name='view_event'),
    path('events/<int:event_id>/delete/', delete_event, name='delete_event'),
    path('events/<int:event_id>/edit/', edit_event, name='edit_event'),

    path('add_participation/', add_participation, name='add_participation'),
    path('participartions/<int:participation_id>/edit/', edit_participation, name='edit_participation'),

    path('generate_report/<int:user_id>/', generate_report, name='generate_report'),
]

volunteerManager/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView

urlpatterns = [
    path("", include("manager.urls")),
    path('admin/', admin.site.urls),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

manager/models.py
from datetime import datetime

from django.db import models


# Create your models here.
class Volunteer(models.Model):
    first_name = models.CharField(max_length=25)
    last_name = models.CharField(max_length=25)
    email = models.EmailField(blank=True)
    phone_number = models.CharField(max_length=15, blank=True)

    is_member = models.BooleanField(default=True)
    is_active_member = models.BooleanField(default=True)

    adherence_date = models.DateField(default=datetime.today)

    BACHELORS = 'Bachelors'
    MASTERS = 'Masters'
    PHD = 'PhD'

    EDUCATION_CHOICES = [
        (BACHELORS, 'Bachelors'),
        (MASTERS, 'Masters'),
        (PHD, 'PhD'),
    ]

    education_level = models.CharField(
        max_length=20,
        choices=EDUCATION_CHOICES,
        default=BACHELORS,
    )

    education_year = models.PositiveSmallIntegerField()

    last_active_date = models.DateField(null=True, blank=True)

    DEPARTMENT_IT = 'IT'
    DEPARTMENT_HR = 'HR'
    DEPARTMENT_PR = 'PR'
    DEPARTMENT_FINANCE = 'FINANCE'

    DEPARTMENT_CHOICES = [
        (DEPARTMENT_IT, 'IT'),
        (DEPARTMENT_HR, 'HR'),
        (DEPARTMENT_PR, 'PR'),
        (DEPARTMENT_FINANCE, 'FINANCE'),
    ]

    department = models.CharField(
        max_length=50,
        choices=DEPARTMENT_CHOICES,
        blank=True,
    )

    def update_last_active_date(self):
        # Get the latest participation date for the volunteer
        latest_participation = self.participation_set.order_by('-event__start_date').first()

        if latest_participation:
            self.last_active_date = latest_participation.event.end_date
            self.save()

    def __str__(self):
        return f'{self.last_name} {self.first_name}'


class Event(models.Model):
    name = models.CharField(max_length=30)
    description = models.TextField()
    start_date = models.DateField(default=datetime.today)
    end_date = models.DateField(default=datetime.today)
    done_reporting = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.name}'


class Participation(models.Model):
    volunteer = models.ForeignKey(Volunteer, on_delete=models.CASCADE)
    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    worked_hours = models.PositiveSmallIntegerField()
    notes = models.TextField()

    def __str__(self):
        return f'{self.volunteer} {self.event}'

templates/add_event.html
{% extends 'base.html' %}

{% block content %}

    <h1>Add Event</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <div class="button-container">
            <button class="btn btn-primary" type="submit">Submit</button>
            <a href="{% url 'events_list' %}" class="btn btn-secondary">Back to Events List</a>
        </div>
    </form>

    <script>
        $(document).ready(function () {
            // Initialize datepicker on the fields with the "datepicker" class
            $('.datepicker').datepicker({
                format: 'yyyy-mm-dd', // You can adjust the format according to your needs
                autoclose: true,
            });
        });
    </script>

{% endblock %}

templates/add_participation.html
{% extends 'base.html' %}

{% block content %}

    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-lg-8">
                <h1 class="mb-4">Add Participation</h1>

                <form method="post">
                    {% csrf_token %}

                    {{ form.non_field_errors }}

                    {% for field in form %}
                        <div class="mb-3">
                            {{ field.label_tag }}
                            {{ field }}
                            {% if field.help_text %}
                                <small class="form-text text-muted">{{ field.help_text }}</small>
                            {% endif %}
                            {% if field.errors %}
                                <div class="invalid-feedback">
                                    {{ field.errors|join:", " }}
                                </div>
                            {% endif %}
                        </div>
                    {% endfor %}

                    <button type="submit" class="btn btn-primary">Submit</button>
                    <a href="{% url 'volunteers_list' %}" class="btn btn-secondary">Back</a>
                </form>
            </div>
        </div>
    </div>

    <script>
        $(document).ready(function () {
            // Initialize Select2 on the fields with the "select2" class
            $('.select2').select2();
        });
    </script>

    <script>
        $(document).ready(function () {
            // Initialize datepicker on the fields with the "datepicker" class
            $('.datepicker').datepicker({
                format: 'yyyy-mm-dd', // You can adjust the format according to your needs
                autoclose: true,
            });
        });
    </script>

{% endblock %}

templates/add_volunteer.html
{% extends 'base.html' %}

{% block content %}

    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <h1 class="mb-4">Add Volunteer</h1>

                <form method="post">
                    {% csrf_token %}

                    {{ form.non_field_errors }}

                    {% for field in form %}
                        {% if field.name != 'last_active_date' %}
                            <div class="mb-3">
                                {{ field.label_tag }}
                                {{ field }}
                                {% if field.help_text %}
                                    <small class="form-text text-muted">{{ field.help_text }}</small>
                                {% endif %}
                                {% if field.errors %}
                                    <div class="invalid-feedback">
                                        {{ field.errors|join:", " }}
                                    </div>
                                {% endif %}
                            </div>
                        {% endif %}
                    {% endfor %}

                    <button type="submit" class="btn btn-primary">Submit</button>
                    <a href="{% url 'volunteers_list' %}" class="btn btn-secondary">Back</a>
                </form>
            </div>
        </div>
    </div>

    <script>
        $(document).ready(function () {
            // Initialize datepicker on the fields with the "datepicker" class
            $('.datepicker').datepicker({
                format: 'yyyy-mm-dd', // You can adjust the format according to your needs
                autoclose: true,
            });
        });
    </script>
    
{% endblock %}

templates/base.html
<!-- templates/base.html -->
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <!-- DataTables CSS -->
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.11.5/css/jquery.dataTables.css">
    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <!-- DataTables JS -->
    <script type="text/javascript" charset="utf8"
            src="https://cdn.datatables.net/1.11.5/js/jquery.dataTables.js"></script>
    <!-- Select2, for searchable dropdowns -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/css/select2.min.css" rel="stylesheet"/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/js/select2.min.js"></script>
    <!-- Bootstrap-datepicker CSS+JS -->
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js"></script>
    <!-- FullCalendar JSON -->
    <script src='https://cdn.jsdelivr.net/npm/fullcalendar@6.1.11/index.global.min.js'></script>

    <link rel="shortcut icon" type="image/png" href="{% static 'images/logo_asf.png' %}">

    <title>Volunteers Manager</title>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-lg navbar-light bg-light mb-3 mx-3">
        <a class="navbar-brand p-1" href="/">Volunteers</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
            <ul class="navbar-nav">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'view_dashboard' %}">Dashboard</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'volunteers_list' %}">Volunteers</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'events_list' %}">Events</a>
                    </li>
                    <div class="dropdown">
                        <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1"
                                data-bs-toggle="dropdown" aria-expanded="false">
                            Welcome, {{ user.username }}
                        </button>
                        <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                            <li>
                                <a class="dropdown-item" href="#">
                                    <form method="post" action="{% url 'logout' %}" class="dropdown-item">
                                        {% csrf_token %}
                                        <button type="submit" class="btn btn-link">Logout</button>
                                    </form>
                                </a>
                            </li>

                        </ul>
                    </div>

                {% else %}
                    <li class="nav-item">
                        <a href="{% url 'login' %}" class="btn btn-primary">Login</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </nav>

</header>

<div class="container-fluid mt-5">
    <main class="text-center">
        <!-- Content for individual pages will be placed here -->
        {% block content %}{% endblock %}
    </main>
</div>

<footer class="mt-5">
    <!-- Your footer content goes here -->
    <p class="text-center">&copy; 2024 Octavian Ianc</p>
</footer>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
        crossorigin="anonymous"></script>
</body>
</html>

templates/dashboard.html
{% extends 'base.html' %}

{% block content %}
    <div class="container mt-5">
        <h1 class="display-4">Dashboard</h1>

        <div class="row mt-4">
            <div class="col-md-4">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Number of Volunteers</h5>
                        <p class="card-text">{{ num_volunteers }}</p>
                    </div>
                </div>
            </div>

            <div class="col-md-4">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Number of Active Volunteers</h5>
                        <p class="card-text">{{ num_active_volunteers }}</p>
                    </div>
                </div>
            </div>

            <div class="col-md-4">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Number of Events</h5>
                        <p class="card-text">{{ num_events }}</p>
                    </div>
                </div>
            </div>
        </div>

        <div class="row mt-4">
            <div class="col-md-6">
                <div class="card">
                    <div class="card-body">
                        <h3>Upcoming Events</h3>
                        <ul class="list-group">
                            {% for event in upcoming_events %}
                                <li class="list-group-item">
                                    <strong>{{ event.name }}</strong> -
                                    {% if event.start_date != event.end_date %}
                                        {{ event.start_date }} - {{ event.end_date }}
                                    {% else %}
                                        {{ event.start_date }}
                                    {% endif %}
                                </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>

            <div class="col-md-6">
                <div class="card p-3">
                    <h3>Calendar</h3>
                    <div id="calendar"></div>
                </div>
            </div>

            <hr class="my-4"> <!-- Horizontal line -->

            <div class="statistics">
                <h3 class="mt-2 mb-4">Statistics</h3>

                <div class="row">
                    <div class="col-md-6">
                        {% if chart_image %}
                            <div class="card">
                                <img src="data:image/png;base64,{{ chart_image }}" alt="Worked Hours per Month">
                            </div>
                        {% endif %}
                    </div>

                    <div class="col-md-6">
                        {% if chart_image %}
                            <div class="card">
                                <img src="data:image/png;base64,{{ adherences_chart_image }}" alt="Adherences Per Year">
                            </div>
                        {% endif %}
                    </div>
                </div>

                <div class="row mt-4">
                    <div class="col-md-6">
                        {% if department_chart_image %}
                            <div class="card">
                                <img src="data:image/png;base64,{{ department_chart_image }}"
                                     alt="Worked Hours per Month">
                            </div>
                        {% endif %}
                    </div>
                </div>
            </div>

        </div>


    </div>


    <script>

        document.addEventListener('DOMContentLoaded', function () {
            var calendarEl = document.getElementById('calendar');
            var calendar = new FullCalendar.Calendar(calendarEl, {
                initialView: 'dayGridMonth',
                events: [
                    {% for event in events_calendar %}
                        {
                            title: "{{ event.title}}",
                            start: '{{ event.start}}',
                            end: '{{ event.end}}',
                            url: '{% url "view_event" event.id %}'
                        },
                    {% endfor %}
                ]
            });


            calendar.render();
        })
        ;

    </script>

{% endblock %}

templates/delete_event.html
{% extends 'base.html' %}

{% block content %}

<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6 bg-white p-4 rounded">
            <h1 class="mb-4">Delete Event</h1>
            <p class="mb-4">Are you sure you want to delete the event "{{ event.name }}"?</p>
            <form method="post">
                {% csrf_token %}
                <button type="submit" name="delete" class="btn btn-danger">Delete</button>
            </form>
            <a href="{% url 'events_list' %}" class="btn btn-secondary mt-2">Cancel</a>
        </div>
    </div>
</div>

{% endblock %}

templates/edit_event.html
{% extends 'base.html' %}

{% block content %}

    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <h1 class="mb-4">Edit Event</h1>

                <form method="post">
                    {% csrf_token %}

                    {{ form.non_field_errors }}

                    {% for field in form %}
                        <div class="mb-3">
                            {{ field.label_tag }}
                            {{ field }}
                            {% if field.help_text %}
                                <small class="form-text text-muted">{{ field.help_text }}</small>
                            {% endif %}
                            {% if field.errors %}
                                <div class="invalid-feedback">
                                    {{ field.errors|join:", " }}
                                </div>
                            {% endif %}
                        </div>
                    {% endfor %}

                    <button type="submit" class="btn btn-primary">Save Changes</button>
                    <a href="{% url 'view_event' event_id=event.id %}" class="btn btn-secondary">Cancel</a>
                </form>
            </div>
        </div>
    </div>

    <script>
        $(document).ready(function () {
            // Initialize datepicker on the fields with the "datepicker" class
            $('.datepicker').datepicker({
                format: 'yyyy-mm-dd', // You can adjust the format according to your needs
                autoclose: true,
            });
        });
    </script>


{% endblock %}

templates/edit_participation.html
{% extends 'base.html' %}

{% block content %}

    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <h1 class="mb-4">Edit Participation</h1>

                <form method="post">
                    {% csrf_token %}

                    {{ form.non_field_errors }}

                    {% for field in form %}
                        <div class="mb-3">
                            {{ field.label_tag }}
                            {{ field }}
                            {% if field.help_text %}
                                <small class="form-text text-muted">{{ field.help_text }}</small>
                            {% endif %}
                            {% if field.errors %}
                                <div class="invalid-feedback">
                                    {{ field.errors|join:", " }}
                                </div>
                            {% endif %}
                        </div>
                    {% endfor %}

                    <button type="submit" class="btn btn-primary">Save Changes</button>
                    <a href="{% url 'view_event' event_id=participation.event.id %}"
                       class="btn btn-secondary">Cancel</a>
                </form>
            </div>
        </div>
    </div>

    <script>
        $(document).ready(function () {
            // Initialize datepicker on the fields with the "datepicker" class
            $('.datepicker').datepicker({
                format: 'yyyy-mm-dd', // You can adjust the format according to your needs
                autoclose: true,
            });
        });
    </script>


{% endblock %}

templates/edit_volunteer.html
{% extends 'base.html' %}

{% block content %}

    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <h1 class="mb-4">Edit Volunteer</h1>

                <form method="post">
                    {% csrf_token %}

                    {{ form.non_field_errors }}

                    {% for field in form %}
                        <div class="mb-3">
                            {{ field.label_tag }}
                            {{ field }}
                            {% if field.help_text %}
                                <small class="form-text text-muted">{{ field.help_text }}</small>
                            {% endif %}
                            {% if field.errors %}
                                <div class="invalid-feedback">
                                    {{ field.errors|join:", " }}
                                </div>
                            {% endif %}
                        </div>
                    {% endfor %}

                    <button type="submit" class="btn btn-primary">Save Changes</button>
                    <a href="{% url 'view_volunteer' user_id=volunteer.id %}" class="btn btn-secondary">Cancel</a>
                </form>
            </div>
        </div>
    </div>

    <script>
        $(document).ready(function () {
            // Initialize datepicker on the fields with the "datepicker" class
            $('.datepicker').datepicker({
                format: 'yyyy-mm-dd', // You can adjust the format according to your needs
                autoclose: true,
            });
        });
    </script>

{% endblock %}

templates/events_list.html
{% extends 'base.html' %}

{% block content %}

    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <h1 class="mb-4 display-4">Events List</h1>

                <table id="eventsTable" class="table table-striped">
                    <thead>
                    <tr>
                        <th>Name</th>
                        <th>Description</th>
                        <th>Start Date</th>
                        <th>End Date</th>
                        <th>Total Worked Hours</th>
                        <th>Total Participants</th>
                        <th>Done reporting</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for event in events %}
                        <tr>
                            <td><a href="{% url 'view_event' event.id %}">{{ event.name }}</a></td>
                            <td class="max-width-description">{{ event.description }}</td>
                            <td>{{ event.start_date }}</td>
                            <td>{{ event.end_date }}</td>
                            <td>{{ event.total_hours }}</td>
                            <td>{{ event.total_participants }}</td>
                            <td>
                                {% if event.done_reporting %}
                                    <p class="text-success">Yes</p>
                                {% else %}
                                    <span class="text-danger">No</span>
                                {% endif %}
                            </td>

                        </tr>
                    {% endfor %}
                    </tbody>
                </table>

                <a href="{% url 'add_event' %}" class="btn btn-primary">Add Event</a>
                <a href="{% url 'volunteers_list' %}" class="btn btn-secondary">Go to Volunteers List</a>
            </div>
        </div>
    </div>

    <style>
        .max-width-description {
            max-width: 300px; /* Adjust the value as needed */
            overflow: hidden;
            text-overflow: ellipsis;
        }
    </style>

    <script>
        $(document).ready(function () {
            var table = $('#eventsTable').DataTable({
                "paging": true,
                "ordering": true,
                "info": true,
                "searching": true,
                "columnDefs": [
                    {"type": "date", "targets": 3},
                    {"type": "num", "targets": [4, 5]}
                ],
                "order": [[3, 'desc']]
            });

            // Add dropdown filters
            table.columns([6]).every(function () {
                var column = this;

                var select = $('<select><option value=""></option></select>')
                    .appendTo($(column.header()))
                    .on('change', function () {
                        var val = $.fn.dataTable.util.escapeRegex(
                            $(this).val()
                        );

                        column
                            .search(val ? '^' + val + '$' : '', true, false)
                            .draw();
                    });

                // Extract text content of cells, excluding any HTML tags
                column.data().unique().sort().each(function (d, j) {
                    var text = $('<div>').html(d).text(); // Extract text content
                    select.append('<option value="' + text + '">' + text + '</option>');
                });
            });
        });

    </script>


{% endblock %}

templates/view_volunteer.html
{% extends 'base.html' %}

{% block content %}

    <div class="container mt-3">
        <div class="col-md-14">
            <h1 class="mb-4">User Details</h1>

            <div class="row">
                <div class="col-md-6">
                    <p><strong>Name:</strong> {{ volunteer.first_name }} {{ volunteer.last_name }}</p>
                    <p><strong>Email:</strong> {{ volunteer.email }}</p>
                    <p><strong>Phone Number:</strong> {{ volunteer.phone_number }}</p>
                    <p><strong>Education Level:</strong> {{ volunteer.get_education_level_display }}</p>
                    <p><strong>Education Year:</strong> {{ volunteer.education_year }}</p>
                    <p><strong>Department:</strong> {{ volunteer.department }}</p>
                </div>

                <div class="col-md-6">
                    <p><strong>Is Member:</strong> {% if volunteer.is_member %}Yes{% else %}No{% endif %}</p>
                    <p><strong>Is Active Member:</strong> {% if volunteer.is_active_member %}Yes{% else %}No{% endif %}
                    </p>
                    <p><strong>Adherence Date:</strong> {{ volunteer.adherence_date }}</p>
                    <p><strong>Last Active Date:</strong> {{ volunteer.last_active_date }}</p>
                    <p class="mt-2"><strong>Total Hours:</strong> {{ total_hours }} hours</p>
                </div>
            </div>
        </div>


        <h2>Participations</h2>
        <table class="table table-striped" id="participationsTable">
            <thead>
            <tr>
                <th>Event</th>
                <th>Date</th>
                <th>Notes</th>
                <th>Worked Hours</th>
                <th>Actions</th>
            </tr>
            </thead>
            <tbody>
            {% for participation in participations %}
                <tr>
                    <td>
                        <a href="{% url 'view_event' event_id=participation.event.id %}">
                            {{ participation.event.name }}
                        </a>
                    </td>


                    <td>
                        {% if participation.event.start_date != participation.event.end_date %}
                            {{ participation.event.start_date }} - {{ participation.event.end_date }}
                        {% else %}
                            {{ participation.event.start_date }}
                        {% endif %}
                    </td>

                    <td>{{ participation.notes }}</td>
                    <td>{{ participation.worked_hours }} hours</td>
                    <td>
                        <div class="row justify-content-center">
                            <div class="col-auto">
                                <a href="{% url 'edit_participation' participation_id=participation.id %}"
                                   class="btn btn-primary">Edit</a>
                            </div>
                            <div class="col-auto">
                            <form method="post" style="display: inline;">
                                {% csrf_token %}
                                <input type="hidden" name="delete_participation" value="{{ participation.id }}">
                                <button type="submit" name="delete_participation_button" class="btn btn-danger">
                                    Delete
                                </button>
                            </form>
                            </div>
                        </div>
                    </td>

                </tr>
            {% endfor %}
            </tbody>
        </table>


        <div class="container mt-3">
            <div class="row justify-content-center">
                <div class="col-auto">
                    <a href="{% url 'edit_volunteer' user_id=volunteer.id %}" class="btn btn-primary">Edit Volunteer</a>
                </div>
                <div class="col-auto">
                    <form method="post">
                        {% csrf_token %}
                        <button type="submit" name="delete" class="btn btn-danger">Delete Volunteer</button>
                    </form>
                </div>
                <div class="col-auto">
                    <a href="{% url 'generate_report' volunteer.id %}" class="btn btn-primary"> Generate PDF report</a>
                </div>
                <div class="col-auto">
                    <a href="{% url 'volunteers_list' %}" class="btn btn-secondary">Back</a>
                </div>
            </div>
        </div>

    </div>
    <script>
        $(document).ready(function () {
            var table = $('#participationsTable').DataTable({
                "paging": true,
                "ordering": true,
                "info": true,
                "searching": true,
            });
        });
    </script>
{% endblock %}